# Generated by Django 5.0.2 on 2024-02-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_earnings_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='quickstart.farmer'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quickstart.crop'),
        ),
    ]
