# Generated by Django 5.0.2 on 2024-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_crop_farmer_alter_earnings_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
