# Generated by Django 5.0.2 on 2024-02-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_farmer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='quickstart.crop'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='quickstart.farmer'),
        ),
    ]
