# Generated by Django 5.0.2 on 2024-02-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alter_earnings_crop_alter_earnings_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='crop',
        ),
    ]
