# Generated by Django 5.0.2 on 2024-02-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_alter_earnings_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='crop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='quickstart.crop'),
        ),
    ]
