# Generated by Django 5.0.2 on 2024-02-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_alter_earnings_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='crop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='quickstart.crop'),
            preserve_default=False,
        ),
    ]
