# Generated by Django 5.0.2 on 2024-02-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_alter_earnings_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='crop',
        ),
        migrations.AlterField(
            model_name='earnings',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='quickstart.farmer'),
        ),
    ]
